name: project_message_demo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  assets_audio_player: ^3.0.3+3
  cached_network_image: ^3.0.0
  cloud_firestore: ^2.2.0
  cloud_functions: ^1.1.0
  cupertino_icons: ^1.0.3
  firebase_auth: ^1.2.0
  firebase_database: ^7.0.0
  firebase_messaging: ^10.0.0
  firebase_storage: ^8.1.0
  # flutter_icons: ^1.1.0
  flutter_webrtc: ^0.6.3
  image_picker: ^0.7.5+2
  intl: ^0.17.0
  photo_view: ^0.11.1
  provider: ^5.0.0
  rflutter_alert: ^2.0.2
  sdp_transform: ^0.3.0
  # simple_animations: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/
